a = set()
b = int(input("Enter number:"))
a.add(b)
c = int(input("Enter number:"))
a.add(c)
d = int(input("Enter number:"))
a.add(d)
e = int(input("Enter number:"))
a.add(e)
f = int(input("Enter number:"))
a.add(f)
g = int(input("Enter number:"))
a.add(g)
h = int(input("Enter number:"))
a.add(h)
i = int(input("Enter number:"))
a.add(i)
print(a)