s = {}
a = input("Ritika's favourite subject is: ")
s.update({"Ritika": a})
b = input("Ritika's favourite subject is: ")
s.update({"Ritika": b})
c = input("Sonia's favourite subject is: ")
s.update({"Sonia": c})
d = input("Neha's favourite subject is: ")
s.update({"Neha": d})
print(s)