a = input("Enter first number: ")
b = input("Enter second number: ")
print("first number is: " , a)
print("second number is: " , b)
print("the sum is:", a+b)

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("first number is: " , a)
print("second number is: " , b)
print("the sum is:", a+b)