fruits = []
a = input("Enter first fruit: ")
b = input("Enter second fruit: ")
c = input("Enter third fruit: ")
d = input("Enter fourth fruit: ")
e = input("Enter fifth fruit: ")
f = input("Enter sixth fruit: ")
g = input("Enter seventh fruit: ")
fruits.append(a)
fruits.append(b)
fruits.append(c)
fruits.append(d)
fruits.append(e)
fruits.append(f)
fruits.append(g)
print(fruits)
