marks=[]
a=input("Enter marks:")
b=input("Enter marks:")
c=input("Enter marks:")
d=input("Enter marks:")
e=input("Enter marks:")
f=input("Enter marks:")
marks.append(a)
marks.append(b)
marks.append(c)
marks.append(d)
marks.append(e)
marks.append(f)
marks.sort()
print(marks)
