list = [ 9, 3, 16, 34, 21, 11]
print(list)
list.sort()
print(list)
list.reverse()
print(list)
list.append(67)
print(list)
list.insert(2, 45)
print(list)
list.remove(34)
print(list)
list.pop()
print(list)